all:
  hosts:
    node1:
      ansible_host: 10.154.0.15
      ip: 10.154.0.15
      access_ip: 10.154.0.15
    node2:
      ansible_host: 10.154.0.16
      ip: 10.154.0.16
      access_ip: 10.154.0.16
    node3:
      ansible_host: 10.154.0.17
      ip: 10.154.0.17
      access_ip: 10.154.0.17
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
