global:
  scrape_interval: 15s
  external_labels:
    cluster: master
    slave: 'false'
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="prometheus"}'
        - '{job="node"}'
        - '{__name__=~".+"}'
        - '{__name__=~"job:.*"}'
    static_configs:
      - targets:
        - 'X.X.X.X:YYYYY'
        - 'X.X.X.X:YYYYY'
