# This segment is for minio setting details
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spin-minio-pv-claim
  namespace: SPINNAKER_NAMESPACE
  labels:
    app: minio-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: SPINNAKER_NAMESPACE
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: spin-minio-pv-claim
      containers:
      - name: minio
        image: docker.io/minio/minio:latest
        args: 
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: username
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: password
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: storage 
          mountPath: "/storage"


---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: SPINNAKER_NAMESPACE
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
    
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: SPINNAKER_NAMESPACE
type: Opaque
data:
  username: base64convertedaccesskey
  password: base64convertedSecretAccesskey


        


